export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER USER BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER USER SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER USER ERROR'